### ISSUE TITLE
Lambda function missing

### ISSUE THREAD

**Issue by jroberayalas** [GokuMohandas/madewithml#182]
Hi Goku,

I'm going through the [Pandas](https://madewithml.com/courses/ml-foundations/pandas/) and I noticed that in the Feature engineering section, you mentioned about applying a lambda function to create a new feature, but the code for it does not appear. I think it's just a minor typo.

Regards,
Roberto

**Comment by GokuMohandas** [comment]
Thank @jroberayalas, you're right, the code was commented out. Thanks, all fixed now!

**Comment by JellenRoberts** [comment]
I have been included on these emails and been trying to unsubscribe to no
avail. Anyone have any ideas on how to fix this?

Thank you!
