### ISSUE TITLE
feature.json not found

### ISSUE THREAD

**Issue by kpputhiyattil** [GokuMohandas/MadeWithML#193]
ERROR: failed to pull data from the cloud - Checkout failed for following targets:
features.json
projects.json
tags.json
features.parquet

**Comment by GokuMohandas** [comment]
features.json is actually a file you generate as you follow along the course and the dvc file is a just a pointer file that points to the actual file in your blob storage. However, if you just wanted to go through a section in isolation which depends on features.json. You can just create the features Dataframe using the actual datasets and the columns the feature DataFrame has.
