### ISSUE TITLE
Module not imported but called in the section Evaluating Machine Learning Model section

### ISSUE THREAD

**Issue by sahajrajmalla** [GokuMohandas/MadeWithML#205]
The website link https://madewithml.com/courses/mlops/evaluation/#intuition of Coarse-grained section suggests to import function `precision_recall_curve` by

```python
from sklearn.metrics import precision_recall_curve
```

but another function `precision_recall_fscore_support` from the same module path is called for computing evaluation metrics by

```python
overall_metrics = precision_recall_fscore_support(y_test, y_pred, average="weighted")
```

**Comment by GokuMohandas** [comment]
Good catch, thank you @sahajrajmalla. I'll push the updates later this week with some more incoming changes.
